// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
declare namespace IndexScssNamespace {
  export interface IIndexScss {
    trafficLight: string;
  }
}

declare const IndexScssModule: IndexScssNamespace.IIndexScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IndexScssNamespace.IIndexScss;
};

export = IndexScssModule;
