// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
declare namespace CommonStylesScssNamespace {
  export interface ICommonStylesScss {
    active: string;
    flashing: string;
    greenLight: string;
    light: string;
    redLight: string;
    yellowLight: string;
  }
}

declare const CommonStylesScssModule: CommonStylesScssNamespace.ICommonStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CommonStylesScssNamespace.ICommonStylesScss;
};

export = CommonStylesScssModule;
